### PR TITLE
Ultimate Ghost update

### PR DESCRIPTION
**Pull request by MunGell**
Hi guys,

I've done a couple of changes in the repository that make upgrading process much easier. All you need to do now is just run `npm update` in root directory (see updated README.md for more information).

Also, this PR includes upgrade to Ghost 0.5.7.

### CODE REVIEW

**Comment by MunGell** [comment]
Hi @corey112358,

Is there any chance you will be able to take a look at this PR?

Thanks

**Comment by MunGell** [comment]
PR updated to Ghost 0.5.8 with following commands:

```
npm update
cp -r node_modules/ghost/content/themes/casper/ content/themes
```

If you installed your blog with the code from this PR – just run these commands in your repository.

**Comment by fluxcorenz** [comment]
Should the casper theme copy command be `cp -r node_modules/ghost/content/themes/casper content/themes`? Or are the files supposed to dump straight into the content/themes directory?

**Comment by MunGell** [comment]
It should be  `cp -r node_modules/ghost/content/themes/casper content/themes`, so it will copy `casper` directory to `content/themes`. 

```
$ ls content/themes
casper/
```

**Comment by tvvocold** [comment]
@MunGell Thx for ur update!
BTW, I think u should update the README.md file also.
If openshift wouln't  merged ur PR  , Just submit it (out of date) to bugzilla or something.

**Comment by MunGell** [comment]
@tvvocold thank you!
I was thinking to change the whole README file to make it look prettier/cleaner, but if you have any particular suggestions I will be glad to hear them. 

By bugzilla, do you mean https://bugzilla.redhat.com/ - this one?

**Comment by tvvocold** [comment]
@MunGell Yup,u can submit OpenShift's bug as well.
My suggestion is add a feature or shell could make update easier like [brettof86' PR](https://github.com/openshift-quickstart/openshift-ghost-quickstart/pull/38/files)

**Comment by MunGell** [comment]
Thank you! I will take a look at this.

**Comment by corey112358** [comment]
I'll try to check out this update this week.

**Comment by tvvocold** [comment]
BTW, Is there anyway i can serving Static Files alongside ghost  in openshift?

**Comment by tvvocold** [comment]
@danmcp @corey112358 
Cannot  create a scable ghost app in openshift by this:
```
rhc app create ghost nodejs-0.10 --env NODE_ENV=production --from-code https://github.com/MunGell/openshift-ghost-quickstart.git -s
```

**Comment by MunGell** [comment]
Hey @tvvocold, this repository contains SQLite version of Ghost and as it is noted in Readme file – it is not scalable at the moment.

Let me test this code on my side (I am currently experiencing problems with logging in into OpenShift) – maybe there is an error after the update.

**Comment by MunGell** [comment]
@tvvocold I found the problem and will update the repository shortly.

The problem is in new compiled SQLite3 driver

**Comment by MunGell** [comment]
The issue with database was fixed. Ghost updated to 0.5.10

**Comment by tvvocold** [comment]
@MunGell 
Thx! Since the OpenShift' team won't merge ur PR(at least not now), could u plz update the md file and open issue feature in ur repo?

**Comment by tvvocold** [comment]
@MunGell BTW, how can i server the static files in CDN? which file should i modify?

**Comment by MunGell** [comment]
I don't have answer to your question, I think it is better to ask it on StackOverFlow.

**Comment by corey112358** [comment]
@MunGell Can you rebase this PR so that it can be merged by github?

**Comment by MunGell** [comment]
Rebased.

I have checked it now – it is still working

**Pull request merged**
