### PR TITLE
Update to 0.7.5

### PR DESCRIPTION
**Pull request by MunGell**

### CODE REVIEW

**Comment by jwulf** [comment]
For those who can't wait - this works:

https://chimpiq.com/update-openshift-ghost-quickstart/

**Comment by MunGell** [comment]
@corey112358

**Comment by jsvgoncalves** [comment]
@MunGell  I'll take a look into this. Can you rebase into a single commit for a cleaner merge?

**Comment by MunGell** [comment]
Hey @jsvgoncalves,

Done, also updated to 0.7.5

**Pull request merged**
